#!/usr/bin/env node
// Extra Gig Pack definitions (British pub + restaurant) merged into build-packs.js
"use strict";
module.exports = [
  {
    id: "british-pub",
    name: "British Pub Gig Pack",
    tagline: "Terrace anthems, indie singalongs and last-orders classics — the full pub setlist.",
    price: 9.99,
    vibes: ["Warm-up & classics", "Indie & terrace anthems", "Last-orders singalongs"],
    songs: [
      ["Wonderwall", "Oasis"], ["Don't Look Back in Anger", "Oasis"], ["Champagne Supernova", "Oasis"],
      ["Live Forever", "Oasis"], ["Stand By Me", "Oasis"], ["Roll With It", "Oasis"], ["Whatever", "Oasis"],
      ["Hey Jude", "The Beatles"], ["Let It Be", "The Beatles"], ["Twist and Shout", "The Beatles"],
      ["Yellow Submarine", "The Beatles"], ["All You Need Is Love - Remastered 2009", "The Beatles"],
      ["Don't Stop Me Now", "Queen"], ["We Will Rock You", "Queen"], ["We Are the Champions", "Queen"],
      ["Another One Bites the Dust", "Queen"], ["Mr. Brightside", "The Killers"], ["Somebody Told Me", "The Killers"],
      ["I Bet You Look Good on the Dancefloor", "Arctic Monkeys"], ["Do I Wanna Know?", "Arctic Monkeys"],
      ["505", "Arctic Monkeys"], ["R U Mine?", "Arctic Monkeys"], ["Fluorescent Adolescent", "Arctic Monkeys"],
      ["I'm Gonna Be (500 Miles)", "The Proclaimers"], ["Come On Eileen", "Dexys Midnight Runners"],
      ["Wake Me Up Before You Go-Go", "Wham!"], ["Take On Me", "a-ha"],
      ["Livin' On A Prayer", "Bon Jovi"], ["You Give Love a Bad Name", "Bon Jovi"],
      ["Don't Stop Believin'", "Journey"], ["Sweet Caroline", "Neil Diamond"], ["Brown Eyed Girl", "Van Morrison"],
      ["American Pie", "Don McLean"], ["Rockin' All Over the World", "Status Quo"],
      ["Town Called Malice", "The Jam"], ["Going Underground", "The Jam"],
      ["Should I Stay or Should I Go", "The Clash"], ["London Calling", "The Clash"],
      ["Ghost Town", "The Specials"], ["A Message to You Rudy", "The Specials"], ["Too Much Too Young", "The Specials"],
      ["Baggy Trousers", "Madness"], ["Our House", "Madness"], ["One Step Beyond", "Madness"],
      ["Red Red Wine", "UB40"], ["(I Can't Help) Falling in Love with You", "UB40"],
      ["Cum On Feel the Noize", "Slade"], ["Merry Xmas Everybody", "Slade"],
      ["Lola", "The Kinks"], ["You Really Got Me", "The Kinks"], ["Waterloo Sunset", "The Kinks"],
      ["Pinball Wizard", "The Who"], ["My Generation", "The Who"], ["Baba O'Riley", "The Who"],
      ["(I Can't Get No) Satisfaction", "The Rolling Stones"], ["Brown Sugar", "The Rolling Stones"],
      ["Start Me Up", "The Rolling Stones"], ["Paint It Black", "The Rolling Stones"],
      ["Smoke on the Water", "Deep Purple"], ["Back in Black", "AC/DC"], ["Highway to Hell", "AC/DC"],
      ["You Shook Me All Night Long", "AC/DC"], ["Sweet Child O' Mine", "Guns N' Roses"],
      ["Paradise City", "Guns N' Roses"], ["Welcome to the Jungle", "Guns N' Roses"],
      ["Dancing in the Dark", "Bruce Springsteen"], ["Born to Run", "Bruce Springsteen"],
      ["Free Fallin'", "Tom Petty"], ["American Girl", "Tom Petty"],
      ["Sultans of Swing", "Dire Straits"], ["Money for Nothing", "Dire Straits"],
      ["Every Breath You Take", "The Police"], ["Roxanne", "The Police"],
      ["Song 2", "Blur"], ["Parklife", "Blur"], ["Country House", "Blur"], ["Common People", "Pulp"],
      ["Bitter Sweet Symphony", "The Verve"], ["Dakota", "Stereophonics"],
      ["Somewhere Only We Know", "Keane"], ["Chasing Cars", "Snow Patrol"],
      ["Yellow", "Coldplay"], ["Viva La Vida", "Coldplay"], ["Fix You", "Coldplay"],
      ["Ruby", "Kaiser Chiefs"], ["I Predict a Riot", "Kaiser Chiefs"], ["Take Me Out", "Franz Ferdinand"],
      ["Valerie", "Amy Winehouse"], ["Rehab", "Amy Winehouse"],
      ["Rolling in the Deep", "Adele"], ["Someone Like You", "Adele"],
      ["Shape of You", "Ed Sheeran"], ["Perfect", "Ed Sheeran"], ["Galway Girl", "Ed Sheeran"],
      ["Castle on the Hill", "Ed Sheeran"], ["Budapest", "George Ezra"], ["Shotgun", "George Ezra"],
      ["Someone You Loved", "Lewis Capaldi"], ["Human", "Rag'n'Bone Man"],
      ["New Rules", "Dua Lipa"], ["Don't Start Now", "Dua Lipa"], ["One Kiss", "Dua Lipa"],
      ["Back for Good", "Take That"], ["Never Forget", "Take That"],
      ["Angels", "Robbie Williams"], ["Feel", "Robbie Williams"], ["Rock DJ", "Robbie Williams"],
      ["Rocket Man", "Elton John"], ["Tiny Dancer", "Elton John"], ["I'm Still Standing", "Elton John"],
      ["Crocodile Rock", "Elton John"], ["Uptown Girl", "Billy Joel"], ["Piano Man", "Billy Joel"],
      ["Don't You Want Me", "The Human League"], ["Tainted Love", "Soft Cell"], ["Rio", "Duran Duran"],
      ["Gold", "Spandau Ballet"], ["True", "Spandau Ballet"], ["Get It On", "T. Rex"],
      ["YMCA", "Village People"], ["Celebration", "Kool & the Gang"], ["Dancing Queen", "ABBA"],
      ["Mamma Mia", "ABBA"], ["Summer of '69", "Bryan Adams"], ["Walking on Sunshine", "Katrina and the Waves"]
    ]
  },
  {
    id: "restaurant",
    name: "Restaurant Gig Pack",
    tagline: "Mellow, dinner-friendly favourites — background gold that fills the room without clearing it.",
    price: 9.99,
    vibes: ["Early evening (soft & acoustic)", "Peak-time favourites", "Feel-good wind-down"],
    songs: [
      ["Hotel California", "Eagles"], ["Take It Easy", "Eagles"], ["Peaceful Easy Feeling", "Eagles"],
      ["Dreams", "Fleetwood Mac"], ["Go Your Own Way", "Fleetwood Mac"],
      ["Brown Eyed Girl", "Van Morrison"], ["Moondance", "Van Morrison"], ["Crazy Love", "Van Morrison"],
      ["Don't Know Why", "Norah Jones"], ["Come Away with Me", "Norah Jones"], ["Sunrise", "Norah Jones"],
      ["Fly Me to the Moon", "Frank Sinatra"], ["The Way You Look Tonight", "Frank Sinatra"],
      ["My Way", "Frank Sinatra"], ["Haven't Met You Yet", "Michael Bublé"], ["Home", "Michael Bublé"],
      ["At Last", "Etta James"], ["Valerie", "Amy Winehouse"],
      ["Make You Feel My Love", "Adele"], ["Someone Like You", "Adele"], ["Easy on Me", "Adele"],
      ["Perfect", "Ed Sheeran"], ["Photograph", "Ed Sheeran"], ["Thinking Out Loud", "Ed Sheeran"],
      ["Castle on the Hill", "Ed Sheeran"], ["All of Me", "John Legend"],
      ["Just the Way You Are", "Bruno Mars"], ["Count on Me", "Bruno Mars"], ["Talking to the Moon", "Bruno Mars"],
      ["I'm Yours", "Jason Mraz"], ["Lucky", "Jason Mraz"], ["Better Together", "Jack Johnson"],
      ["Banana Pancakes", "Jack Johnson"], ["Riptide", "Vance Joy"], ["Ho Hey", "The Lumineers"],
      ["Take Me to Church", "Hozier"], ["Let Her Go", "Passenger"], ["Somebody That I Used to Know", "Gotye"],
      ["Let It Be", "The Beatles"], ["Hey Jude", "The Beatles"], ["Blackbird", "The Beatles"],
      ["Here Comes the Sun", "The Beatles"], ["In My Life", "The Beatles"], ["Yesterday", "The Beatles"],
      ["Bridge over Troubled Water", "Simon & Garfunkel"], ["The Sound of Silence", "Simon & Garfunkel"],
      ["Mrs. Robinson", "Simon & Garfunkel"], ["Cecilia", "Simon & Garfunkel"],
      ["Fire and Rain", "James Taylor"], ["You've Got a Friend", "James Taylor"], ["Carolina in My Mind", "James Taylor"],
      ["So Far Away", "Carole King"], ["It's Too Late", "Carole King"],
      ["Your Song", "Elton John"], ["Tiny Dancer", "Elton John"], ["Rocket Man", "Elton John"],
      ["Wonderful Tonight", "Eric Clapton"], ["Tears in Heaven", "Eric Clapton"],
      ["Three Little Birds", "Bob Marley"], ["Redemption Song", "Bob Marley"],
      ["No Woman, No Cry", "Bob Marley"], ["Is This Love", "Bob Marley"],
      ["Somewhere Over the Rainbow", "Israel Kamakawiwo'ole"], ["What a Wonderful World", "Louis Armstrong"],
      ["Yellow", "Coldplay"], ["Fix You", "Coldplay"], ["The Scientist", "Coldplay"], ["Viva La Vida", "Coldplay"],
      ["Somewhere Only We Know", "Keane"], ["Chasing Cars", "Snow Patrol"],
      ["Drops of Jupiter", "Train"], ["Hey, Soul Sister", "Train"], ["Hey There Delilah", "Plain White T's"],
      ["You're Beautiful", "James Blunt"], ["Put Your Records On", "Corinne Bailey Rae"],
      ["Everything", "Michael Bublé"], ["Sway", "Michael Bublé"], ["Feeling Good", "Michael Bublé"],
      ["She's the One", "Robbie Williams"], ["You Raise Me Up", "Westlife"],
      ["Stay With Me", "Sam Smith"], ["I'm Not the Only One", "Sam Smith"],
      ["Too Good at Goodbyes", "Sam Smith"], ["Someone You Loved", "Lewis Capaldi"], ["Before You Go", "Lewis Capaldi"],
      ["lovely (with Khalid)", "Billie Eilish"], ["A Thousand Years", "Christina Perri"],
      ["Fireflies", "Owl City"], ["Skinny Love", "Birdy"], ["Daughters", "John Mayer"], ["Gravity", "John Mayer"],
      ["She Used to Be Mine", "Sara Bareilles"], ["Brave", "Sara Bareilles"],
      ["Bubbly", "Colbie Caillat"], ["Realize", "Colbie Caillat"],
      ["Haven't Met You Yet", "Michael Bublé"], ["Sitting, Waiting, Wishing", "Jack Johnson"],
      ["One Love", "Bob Marley"], ["Buffalo Soldier", "Bob Marley"], ["Could You Be Loved", "Bob Marley"],
      ["Stubborn Love", "The Lumineers"], ["Ophelia", "The Lumineers"],
      ["Better Man", "Pearl Jam"], ["Fields of Gold", "Sting"], ["Shape of You", "Ed Sheeran"],
      ["Galway Girl", "Ed Sheeran"], ["Budapest", "George Ezra"], ["Shotgun", "George Ezra"],
      ["Angels", "Robbie Williams"], ["You're Still the One", "Shania Twain"], ["Wonderwall", "Oasis"],
      ["Champagne Supernova", "Oasis"], ["Human", "Rag'n'Bone Man"], ["Skinny Love", "Bon Iver"],
      ["Fast Car", "Tracy Chapman"], ["Sunshine on My Shoulders", "John Denver"],
      ["Annie's Song", "John Denver"], ["Leaving on a Jet Plane", "John Denver"],
      ["Take Me Home, Country Roads", "John Denver"], ["Time After Time", "Cyndi Lauper"],
      ["Total Eclipse of the Heart", "Bonnie Tyler"], ["Killing Me Softly", "The Fugees"],
      ["Fallin'", "Alicia Keys"], ["If I Ain't Got You", "Alicia Keys"], ["No One", "Alicia Keys"],
      ["Empire State of Mind", "Jay-Z"], ["I Will Always Love You", "Whitney Houston"],
      ["Greatest Love of All", "Whitney Houston"], ["Hero", "Mariah Carey"], ["We Belong Together", "Mariah Carey"],
      ["Un-break My Heart", "Toni Braxton"], ["My Heart Will Go On", "Celine Dion"],
      ["Because You Loved Me", "Celine Dion"], ["I Don't Want to Miss a Thing", "Aerosmith"],
      ["Always", "Bon Jovi"], ["November Rain", "Guns N' Roses"], ["Every Rose Has Its Thorn", "Poison"],
      ["More Than Words", "Extreme"], ["To Be With You", "Mr. Big"], ["Iris", "Goo Goo Dolls"],
      ["Slide", "Goo Goo Dolls"], ["Kiss from a Rose", "Seal"], ["Fields of Gold", "Sting"],
      ["Shape of You", "Ed Sheeran"], ["Thinking Out Loud", "Ed Sheeran"], ["Perfect", "Ed Sheeran"]
    ]
  }
];
