var TOP50 = [
    ["Earrings", "Malcolm Todd", "", ""],
    ["Loser", "Tame Impala", "", ""],
    ["Beauty And A Beat", "Justin Bieber", "", ""],
    ["Dai Dai", "Shakira", "", ""],
    ["Self Aware", "Temper City", "", ""],
    ["The One That Got Away", "Katy Perry", "", ""],
    ["BbY WOW", "KAROL G", "", ""],
    ["the cure", "Olivia Rodrigo", "", ""],
    ["Babydoll", "Dominic Fike", "", ""],
    ["hate that i made you love me", "Ariana Grande", "", ""],
    ["Iris", "The Goo Goo Dolls", "", ""],
    ["SWIM", "BTS", "", ""],
    ["Billie Jean", "Michael Jackson", "", ""],
    ["stupid song", "Olivia Rodrigo", "", ""],
    ["back to friends", "sombr", "", ""],
    ["Wonderwall", "Oasis", "", ""],
    ["Sunflower", "Post Malone", "", ""],
    ["Choosin' Texas", "Ella Langley", "", ""],
    ["Treat You Better", "Shawn Mendes", "", ""],
    ["Love Me Not", "Ravyn Lenae", "", ""],
    ["Die With A Smile", "Lady Gaga", "", ""],
    ["End of Beginning", "Djo", "", ""],
    ["Animal", "KATSEYE", "", ""],
    ["Man I Need", "Olivia Dean", "", ""],
    ["Hootie Frutti", "KATSEYE", "", ""],
    ["Jolene", "Dolly Parton", "", ""],
    ["Teh Hijau", "Tulus", "", ""],
    ["drop dead", "Olivia Rodrigo", "", ""],
    ["Ordinary", "Alex Warren", "", ""],
    ["oh yeah?", "Steve Lacy", "", ""],
    ["Sweater Weather", "The Neighbourhood", "", ""],
    ["Risk It All", "Bruno Mars", "", ""],
    ["Sailor Song", "Gigi Perez", "", ""],
    ["BIRDS OF A FEATHER", "Billie Eilish", "", ""],
    ["Jamaican (Bam Bam)", "HUGEL", "", ""],
    ["Cinderella", "Mac Miller", "", ""],
    ["Sesi Potret", "eńau", "", ""],
    ["The Fate of Ophelia", "Taylor Swift", "", ""],
    ["petal", "Ariana Grande", "", ""],
    ["Mr. Brightside", "The Killers", "", ""],
    ["DtMF", "Bad Bunny", "", ""],
    ["Ain't In LA", "ADÉLA", "", ""],
    ["Riptide", "Vance Joy", "", ""],
    ["Every Breath You Take", "The Police", "", ""],
    ["Yellow", "Coldplay", "", ""],
    ["EoO", "Bad Bunny", "", ""],
    ["RIKI", "Neton Vega", "", ""],
    ["Creep", "Radiohead", "", ""],
    ["Beat It", "Michael Jackson", "", ""],
    ["Sign of the Times", "Harry Styles", "", ""]
];