var TOP50 = [
    ["Unholy (feat. Kim Petras)", "Sam Smith", "D", "131"],
    ["Quevedo: Bzrp Music Sessions, Vol. 52", "Bizarrap", "D", "128"],
    ["La Bachata", "Manuel Turizo", "G", "125"],
    ["I'm Good (Blue)", "David Guetta", "G", "128"],
    ["Tití Me Preguntó", "Bad Bunny", "F", "107"],
    ["Me Porto Bonito", "Bad Bunny", "C#", "92"],
    ["I Ain't Worried", "OneRepublic", "C", "140"],
    ["Under The Influence", "Chris Brown", "A", "117"],
    ["Efecto", "Bad Bunny", "G", "98"],
    ["Ojitos Lindos", "Bad Bunny", "D#", "80"],
    ["Glimpse of Us", "Joji", "G#", "170"],
    ["Moscow Mule", "Bad Bunny", "F", "100"],
    ["Sweater Weather", "The Neighbourhood", "A#", "124"],
    ["Neverita", "Bad Bunny", "A#", "122"],
    ["CUFF IT", "Beyoncé", "G", "115"],
    ["Another Love", "Tom Odell", "E", "123"],
    ["PROVENZA", "KAROL G", "C#", "111"],
    ["Calm Down (with Selena Gomez)", "Rema", "B", "107"],
    ["I Wanna Be Yours", "Arctic Monkeys", "C", "68"],
    ["Left and Right (Feat. Jung Kook of BTS)", "Charlie Puth", "D", "101"],
    ["LOKERA", "Rauw Alejandro", "B", "102"],
    ["Caile", "Luar La L", "C", "122"],
    ["Tarot", "Bad Bunny", "B", "114"],
    ["Jimmy Cooks (feat. 21 Savage)", "Drake", "C", "166"],
    ["Running Up That Hill (A Deal With God)", "Kate Bush", "A#", "108"],
    ["Ferrari", "James Hype", "C#", "125"],
    ["La Corriente", "Bad Bunny", "B", "196"],
    ["GATÚBELA", "KAROL G", "B", "93"],
    ["Dandelions", "Ruth B.", "C#", "117"],
    ["STAR WALKIN' (League of Legends Worlds Anthem)", "Lil Nas X", "D", "142"],
    ["Party", "Bad Bunny", "A", "97"],
    ["MIDDLE OF THE NIGHT", "Elley Duhé", "E", "186"],
    ["Sex, Drugs, Etc.", "Beach Weather", "E", "144"],
    ["Te Felicito", "Shakira", "F", "174"],
    ["Atlantis", "Seafret", "G#", "166"],
    ["Vegas (From the Original Motion Picture Soundtrack ELVIS)", "Doja Cat", "G#", "160"],
    ["Until I Found You", "Stephen Sanchez", "A#", "101"],
    ["I Was Never There", "The Weeknd", "A#", "113"],
    ["Hold Me Closer", "Elton John", "C", "126"],
    ["Gangsta's Paradise", "Coolio", "G#", "80"],
    ["WAIT FOR U (feat. Drake & Tems)", "Future", "C#", "83"],
    ["One Kiss (with Dua Lipa)", "Calvin Harris", "A", "124"],
    ["Bones", "Imagine Dragons", "F", "114"],
    ["LA INOCENTE", "Mora", "F", "92"],
    ["cómo dormiste?", "Rels B", "C#", "126"],
    ["lovely (with Khalid)", "Billie Eilish", "E", "115"],
    ["I Love You So", "The Walters", "A#", "76"],
    ["STAY (with Justin Bieber)", "The Kid LAROI", "C#", "170"],
    ["BILLIE EILISH.", "Armani White", "C#", "100"],
    ["No Role Modelz", "J. Cole", "A#", "100"]
];